import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "DinkDrills — AI-Powered Pickleball Training Plans",
  description:
    "Get a personalized pickleball training plan generated by AI based on your skill level, weaknesses, and available time.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
